MODEL:
  META_ARCHITECTURE: 'inception_v3'
  NUM_CLASSES: 1000
INPUT:
  RESIZE_SIZE: 300
  IMAGE_SIZE: 299
DATASETS:
  TRAIN: ("imagenet_train",)
  TEST: ("imagenet5k_val",)
SOLVER:
  MAX_ITER: 120000
  LR_STEPS: [80000, 100000]
  GAMMA: 0.1
  BATCH_SIZE: 16
  LR: 1e-3
OUTPUT_DIR: ''

EVAL_MODEL:
  EVAL_DIFFERENT_MODEL_FROM_TRAIN: True
  META_ARCHITECTURE: 'vgg16'
  NUM_CLASSES: 1000


