MODEL:
  NUM_CLASSES: 21
INPUT:
  IMAGE_SIZE: 300
DATASETS:
  # CHANGED
  TRAIN: ("clipart_train",)
  TRAIN_OOD: ("clipart_test",)

  TEST: ("clipart_test", )
SOLVER:
  MAX_ITER: 120000
  LR_STEPS: [80000, 100000]
  GAMMA: 0.1
  BATCH_SIZE: 32
  LR: 1e-3

OUTPUT_DIR: 'vgg_ssd300_clipart'
