MODEL:
  NUM_CLASSES: 21
INPUT:
  IMAGE_SIZE: 300
DATASETS:
  TRAIN: ("voc_2007_trainval", "voc_2012_trainval")
  #TRAIN: ("voc_2007_trainval", "voc_2012_trainval", "voc_200712_trainval_ood")

  # CHANGED
  TRAIN_OOD: ("voc_2007_test",)
  #TRAIN_OOD: ("voc_2007_trainval", "voc_2012_trainval")

  TEST: ("voc_2007_test", )
SOLVER:
  MAX_ITER: 120000
  LR_STEPS: [80000, 100000]
  GAMMA: 0.1
  BATCH_SIZE: 32
  LR: 1e-3
OUTPUT_DIR: 'vgg_ssd300_voc0712'
