MODEL:
  NUM_CLASSES: 21
INPUT:
  IMAGE_SIZE: 300
DATASETS:
  TRAIN: ("comic_train",)
  TEST: ("comic_test",)
SOLVER:
  MAX_ITER: 40000
  LR_STEPS: [15000, 25000]
  GAMMA: 0.1
  BATCH_SIZE: 32
  LR: 1e-3

OUTPUT_DIR: 'outputs/vgg_ssd300_comic'
