MODEL:
  NUM_CLASSES: 9
INPUT:
  IMAGE_SIZE: 300
DATASETS:
  TRAIN: ("cityscapes_trainval",)
  TEST: ("cityscapes_test",)
SOLVER:
  MAX_ITER: 120000
  LR_STEPS: [80000, 100000]
  GAMMA: 0.1
  BATCH_SIZE: 32
  LR: 1e-3

OUTPUT_DIR: 'vgg_ssd300_cityscapes'
