MODEL:
  NUM_CLASSES: 2
INPUT:
  IMAGE_SIZE: 300
DATASETS:
  TRAIN: ("sim10k_train",)
  TEST: ("sim10k_test",)
SOLVER:
  MAX_ITER: 120000
  LR_STEPS: [80000, 100000]
  GAMMA: 0.1
  BATCH_SIZE: 32
  LR: 1e-3

OUTPUT_DIR: 'vgg_ssd300_sim10k'
